### ISSUE TITLE
Usage and examples links are broken

### ISSUE THREAD

**Issue by jepsar** [microbean/freemarker-maven-plugin#1]
https://github.com/microbean/freemarker-maven-plugin#usage-and-examples

**Comment by ljnelson** [comment]
How embarrassing!  It looks like the site deployment failed.  I'll correct this later today.  Thanks for your interest in the project.

**Comment by ljnelson** [comment]
Fixed; see https://microbean.github.io/freemarker-maven-plugin/index.html

**Comment by ljnelson** [comment]
Creating new issue for examples (never had them to begin with :smile:)
