### ISSUE TITLE
The example link on your page was broken.

### ISSUE THREAD

**Issue by HaLo1701** [microbean/freemarker-maven-plugin#3]
Hello,
the example link on your page was broken.
I want to implement the plugin in one project and got problems, so i want to compare with your example.
Many thanks in advance.

**Comment by ljnelson** [comment]
Yes; if you mean [this one](https://microbean.github.io/freemarker-maven-plugin/examples.html), that would be due to #2. 😄 

Perhaps you could describe your issue here and if it's not super complicated we could find a solution?

**Comment by ljnelson** [comment]
In the meantime, you may find this helpful:

https://github.com/microbean/freemarker-maven-plugin/blob/d3cb5eb8c44662ac941652a06e73667980f432d0/src/test/projects/valid/pom.xml#L15-L43

**Comment by HaLo1701** [comment]
Hello @ljnelson ,

thank you for the very quick response.
This was exactly what i need, the pom.xml.
I have had problems to configure the templateLoader. With your example, it works now.
Many thanks again.

**Comment by ljnelson** [comment]
Glad to help.
